---
title: "1st-quarter-impact"
output: html_document
---


```{r}
library(tidyverse)
library(brms)
library(tidybayes)
```

```{r}
data = read.csv("espn.com/data/espn-clean-pbp-2022.csv") %>% filter(awayTeam != "STE" & homeTeam != "WIL") 
```

```{r}
data$gameID %>% unique() %>% length()
```

```{r}
q1_data = data %>% filter(Event == "End of Period" & period == 1)
q1_data
```

```{r}
model_data_q1 = q1_data %>% mutate(scoreDiff = homeScore - awayScore) %>% dplyr::select(gameID,homeScore,awayScore,scoreDiff,homeTeam,awayTeam,winner)

#get into long form where there are two rows for each game: one per team
model_data_q1 = model_data_q1 %>% pivot_longer(cols=c("homeTeam","awayTeam"),names_to = "teamSide",values_to = "team") %>%
  mutate(teamSide = gsub("Team","",teamSide)) %>% mutate(won = (winner==teamSide)) %>%
  mutate(scoreDiff = ifelse(teamSide == "home", scoreDiff, -scoreDiff)) %>% dplyr::select(-winner)

model_data_q1
```


```{r}
model_q1_monotonic = brm(won~mo(scoreDiff),data=model_data_q1,family=bernoulli(),chains=4,cores=4,file="win_prob/model_q1_monotonic")
```

```{r}
plot(model_q1_monotonic,ask=F)
```

```{r}
max_scoreDiff = model_data_q1$scoreDiff %>% max()
```


Let's plot the monotonic effect of scoreDiff. On a logit scale, we can see that the effect is linear

```{r}
preds = data.frame(scoreDiff = -max_scoreDiff:max_scoreDiff) %>% add_fitted_draws(model_q1_monotonic) 

preds %>% group_by(scoreDiff) %>% dplyr::summarise(p = sum(.value)/n()) %>% 
  ggplot(aes(x=scoreDiff,y=p)) + geom_point()

preds %>% group_by(scoreDiff) %>% dplyr::summarise(p = sum(.value)/n()) %>% 
  ggplot(aes(x=scoreDiff,y=logit_scaled(p))) + geom_point()

preds %>% group_by(scoreDiff) %>% 
  ggplot(aes(x=scoreDiff,y=logit_scaled(.value))) + stat_lineribbon(.width = .9)
```

```{r}
conditional_effects(model_q1_monotonic)
```


```{r}
model_hier_monotonic = brm(won~1+mo(scoreDiff) + (1+mo(scoreDiff)|team),data=model_data_q1,family=bernoulli(),chains=4,cores=4,file="win_prob/model_q1_hier_monotonic")

model_hier_linear = brm(won~1+scoreDiff + (1+scoreDiff|team),data=model_data_q1,family=bernoulli(),chains=4,cores=4,file="win_prob/model_q1_hier_linear")
```

```{r}
teams = unique(model_data_q1$team)

team_fitted_vals = expand_grid(scoreDiff = -max_scoreDiff:max_scoreDiff, team =teams) %>% 
  add_fitted_draws(model_hier_monotonic) 
team_fitted_vals %>%
  ggplot(aes(x=scoreDiff,y=.value,col=team)) + stat_lineribbon(.width=.9) + facet_wrap(~team)

team_fitted_vals %>%
  group_by(team,scoreDiff) %>% dplyr::summarise(p = mean(.value)) %>%
  ggplot(aes(x=scoreDiff,y=p,col=team)) + geom_line()
```

```{r}
team_fitted_vals = expand_grid(scoreDiff = -max_scoreDiff:max_scoreDiff, team = teams) %>% 
  add_fitted_draws(model_hier_linear) 
team_fitted_vals %>%
  ggplot(aes(x=scoreDiff,y=.value,col=team)) + stat_lineribbon(.width=.9) + facet_wrap(~team)

team_fitted_vals %>%
  group_by(team,scoreDiff) %>% dplyr::summarise(p = mean(.value)) %>%
  ggplot(aes(x=scoreDiff,y=p,col=team)) + geom_line()
```

```{r}
model_hier_monotonic = add_criterion(model_hier_monotonic,"loo")
model_hier_linear = add_criterion(model_hier_linear,"loo")

loo_compare(model_hier_monotonic,model_hier_linear)
```




```{r}
all_q_data = data %>% filter(Event == "End of Period" & text !="End of Game")
```

```{r}
model_data_all_q = all_q_data %>% mutate(scoreDiff = homeScore - awayScore) %>% dplyr::select(gameID,homeScore,awayScore,scoreDiff,homeTeam,awayTeam,winner,period)

#get into long form where there are two rows for each game: one per team
model_data_all_q = model_data_all_q %>% pivot_longer(cols=c("homeTeam","awayTeam"),names_to = "teamSide",values_to = "team") %>%
  mutate(teamSide = gsub("Team","",teamSide)) %>% mutate(won = (winner==teamSide)) %>%
  mutate(scoreDiff = ifelse(teamSide == "home", scoreDiff, -scoreDiff)) %>% dplyr::select(-winner)

model_data_all_q %>% group_by(period,gameID) %>% dplyr::summarize(N=n()) %>% filter(N>2)

model_data_all_q
```

```{r}
model_hier_quarters_monotonic = brm(won~1:period+mo(scoreDiff):period + (1:period+mo(scoreDiff):period|team),data=model_data_all_q,family=bernoulli(),chains=4,cores=4,file="win_prob/model_all_q_linear")

model_hier_quarters_linear = brm(won~1:period+scoreDiff:period + (1:period+scoreDiff:period|team),data=model_data_all_q,family=bernoulli(),chains=4,cores=4,file="win_prob/model_all_q_linear")
```

```{r}
team_fitted_vals = expand_grid(scoreDiff = -max_scoreDiff:max_scoreDiff, team =unique(model_data$team), period = 1:4) %>% 
  add_fitted_draws(model_hier_quarters_monotonic) 

team_fitted_vals %>% filter(period==1) %>%
  ggplot(aes(x=scoreDiff,y=.value,col=team)) + stat_lineribbon(.width=.9) + facet_wrap(~team)

team_fitted_vals %>%
  group_by(team,scoreDiff,period) %>% dplyr::summarise(p = median(.value)) %>%
  ggplot(aes(x=scoreDiff,y=p,col=as.factor(period))) + geom_line() + facet_wrap(~team)
```

```{r}
team_fitted_vals = expand_grid(scoreDiff = -max_scoreDiff:max_scoreDiff, team =unique(model_data$team), period = 1:4) %>% 
  add_fitted_draws(model_hier_quarters_linear) 

team_fitted_vals %>%
  group_by(team,scoreDiff,period) %>% dplyr::summarise(p = mean(.value)) %>%
  ggplot(aes(x=scoreDiff,y=p,col=as.factor(period))) + geom_line() + facet_wrap(~team)
```


```{r}
model_hier_quarters_linear = add_criterion(model_hier_quarters_linear,"loo")
model_hier_quarters_monotonic = add_criterion(model_hier_quarters_monotonic,"loo")

loo_compare(model_hier_quarters_linear,model_hier_quarters_monotonic)
```

